/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as MyClubsRouteImport } from './routes/my-clubs'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as RequestAdminRouteImport } from './routes/request-admin'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminClubsRouteImport } from './routes/admin.clubs'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminTutorialsRouteImport } from './routes/admin.tutorials'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ClubsClubIdRouteImport } from './routes/clubs_.$clubId'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as ManageAnnouncementsRouteImport } from './routes/manage.announcements'
import { Route as ManageEventsRouteImport } from './routes/manage.events'
import { Route as ManageRequestsRouteImport } from './routes/manage.requests'
import { Route as ManageTeamsRouteImport } from './routes/manage.teams'
import { Route as ManageTutorialsRouteImport } from './routes/manage.tutorials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const MyClubsRoute = MyClubsRouteImport.update({
  id: '/my-clubs',
  path: '/my-clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAdminRoute = RequestAdminRouteImport.update({
  id: '/request-admin',
  path: '/request-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClubsRoute = AdminClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTutorialsRoute = AdminTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ClubsClubIdRoute = ClubsClubIdRouteImport.update({
  id: '/clubs_/$clubId',
  path: '/clubs/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRoute,
} as any)
const ManageAnnouncementsRoute = ManageAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => ManageRoute,
} as any)
const ManageEventsRoute = ManageEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ManageRoute,
} as any)
const ManageRequestsRoute = ManageRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => ManageRoute,
} as any)
const ManageTeamsRoute = ManageTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => ManageRoute,
} as any)
const ManageTutorialsRoute = ManageTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => ManageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/calendar': typeof CalendarRoute
  '/clubs': typeof ClubsRoute
  '/manage': typeof ManageRouteWithChildren
  '/my-clubs': typeof MyClubsRoute
  '/owner': typeof OwnerRoute
  '/pending': typeof PendingRoute
  '/request-admin': typeof RequestAdminRoute
  '/teams': typeof TeamsRoute
  '/tutorials': typeof TutorialsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/clubs': typeof AdminClubsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/tutorials': typeof AdminTutorialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/manage/announcements': typeof ManageAnnouncementsRoute
  '/manage/events': typeof ManageEventsRoute
  '/manage/requests': typeof ManageRequestsRoute
  '/manage/teams': typeof ManageTeamsRoute
  '/manage/tutorials': typeof ManageTutorialsRoute
  '/admin/': typeof AdminIndexRoute
  '/manage/': typeof ManageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/announcements': typeof AnnouncementsRoute
  '/calendar': typeof CalendarRoute
  '/clubs': typeof ClubsRoute
  '/my-clubs': typeof MyClubsRoute
  '/owner': typeof OwnerRoute
  '/pending': typeof PendingRoute
  '/request-admin': typeof RequestAdminRoute
  '/teams': typeof TeamsRoute
  '/tutorials': typeof TutorialsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/clubs': typeof AdminClubsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/tutorials': typeof AdminTutorialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/manage/announcements': typeof ManageAnnouncementsRoute
  '/manage/events': typeof ManageEventsRoute
  '/manage/requests': typeof ManageRequestsRoute
  '/manage/teams': typeof ManageTeamsRoute
  '/manage/tutorials': typeof ManageTutorialsRoute
  '/admin': typeof AdminIndexRoute
  '/manage': typeof ManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/calendar': typeof CalendarRoute
  '/clubs': typeof ClubsRoute
  '/manage': typeof ManageRouteWithChildren
  '/my-clubs': typeof MyClubsRoute
  '/owner': typeof OwnerRoute
  '/pending': typeof PendingRoute
  '/request-admin': typeof RequestAdminRoute
  '/teams': typeof TeamsRoute
  '/tutorials': typeof TutorialsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/clubs': typeof AdminClubsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/tutorials': typeof AdminTutorialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/clubs_/$clubId': typeof ClubsClubIdRoute
  '/manage/announcements': typeof ManageAnnouncementsRoute
  '/manage/events': typeof ManageEventsRoute
  '/manage/requests': typeof ManageRequestsRoute
  '/manage/teams': typeof ManageTeamsRoute
  '/manage/tutorials': typeof ManageTutorialsRoute
  '/admin/': typeof AdminIndexRoute
  '/manage/': typeof ManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/announcements'
    | '/calendar'
    | '/clubs'
    | '/manage'
    | '/my-clubs'
    | '/owner'
    | '/pending'
    | '/request-admin'
    | '/teams'
    | '/tutorials'
    | '/verify-email'
    | '/admin/announcements'
    | '/admin/clubs'
    | '/admin/events'
    | '/admin/teachers'
    | '/admin/tutorials'
    | '/admin/users'
    | '/clubs/$clubId'
    | '/manage/announcements'
    | '/manage/events'
    | '/manage/requests'
    | '/manage/teams'
    | '/manage/tutorials'
    | '/admin/'
    | '/manage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/announcements'
    | '/calendar'
    | '/clubs'
    | '/my-clubs'
    | '/owner'
    | '/pending'
    | '/request-admin'
    | '/teams'
    | '/tutorials'
    | '/verify-email'
    | '/admin/announcements'
    | '/admin/clubs'
    | '/admin/events'
    | '/admin/teachers'
    | '/admin/tutorials'
    | '/admin/users'
    | '/clubs/$clubId'
    | '/manage/announcements'
    | '/manage/events'
    | '/manage/requests'
    | '/manage/teams'
    | '/manage/tutorials'
    | '/admin'
    | '/manage'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/announcements'
    | '/calendar'
    | '/clubs'
    | '/manage'
    | '/my-clubs'
    | '/owner'
    | '/pending'
    | '/request-admin'
    | '/teams'
    | '/tutorials'
    | '/verify-email'
    | '/admin/announcements'
    | '/admin/clubs'
    | '/admin/events'
    | '/admin/teachers'
    | '/admin/tutorials'
    | '/admin/users'
    | '/clubs_/$clubId'
    | '/manage/announcements'
    | '/manage/events'
    | '/manage/requests'
    | '/manage/teams'
    | '/manage/tutorials'
    | '/admin/'
    | '/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  CalendarRoute: typeof CalendarRoute
  ClubsRoute: typeof ClubsRoute
  ManageRoute: typeof ManageRouteWithChildren
  MyClubsRoute: typeof MyClubsRoute
  OwnerRoute: typeof OwnerRoute
  PendingRoute: typeof PendingRoute
  RequestAdminRoute: typeof RequestAdminRoute
  TeamsRoute: typeof TeamsRoute
  TutorialsRoute: typeof TutorialsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ClubsClubIdRoute: typeof ClubsClubIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-clubs': {
      id: '/my-clubs'
      path: '/my-clubs'
      fullPath: '/my-clubs'
      preLoaderRoute: typeof MyClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-admin': {
      id: '/request-admin'
      path: '/request-admin'
      fullPath: '/request-admin'
      preLoaderRoute: typeof RequestAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clubs': {
      id: '/admin/clubs'
      path: '/clubs'
      fullPath: '/admin/clubs'
      preLoaderRoute: typeof AdminClubsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tutorials': {
      id: '/admin/tutorials'
      path: '/tutorials'
      fullPath: '/admin/tutorials'
      preLoaderRoute: typeof AdminTutorialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/clubs_/$clubId': {
      id: '/clubs_/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof ClubsClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/announcements': {
      id: '/manage/announcements'
      path: '/announcements'
      fullPath: '/manage/announcements'
      preLoaderRoute: typeof ManageAnnouncementsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/events': {
      id: '/manage/events'
      path: '/events'
      fullPath: '/manage/events'
      preLoaderRoute: typeof ManageEventsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/requests': {
      id: '/manage/requests'
      path: '/requests'
      fullPath: '/manage/requests'
      preLoaderRoute: typeof ManageRequestsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/teams': {
      id: '/manage/teams'
      path: '/teams'
      fullPath: '/manage/teams'
      preLoaderRoute: typeof ManageTeamsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/tutorials': {
      id: '/manage/tutorials'
      path: '/tutorials'
      fullPath: '/manage/tutorials'
      preLoaderRoute: typeof ManageTutorialsRouteImport
      parentRoute: typeof ManageRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminClubsRoute: typeof AdminClubsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminTutorialsRoute: typeof AdminTutorialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminClubsRoute: AdminClubsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminTutorialsRoute: AdminTutorialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ManageRouteChildren {
  ManageAnnouncementsRoute: typeof ManageAnnouncementsRoute
  ManageEventsRoute: typeof ManageEventsRoute
  ManageRequestsRoute: typeof ManageRequestsRoute
  ManageTeamsRoute: typeof ManageTeamsRoute
  ManageTutorialsRoute: typeof ManageTutorialsRoute
  ManageIndexRoute: typeof ManageIndexRoute
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageAnnouncementsRoute: ManageAnnouncementsRoute,
  ManageEventsRoute: ManageEventsRoute,
  ManageRequestsRoute: ManageRequestsRoute,
  ManageTeamsRoute: ManageTeamsRoute,
  ManageTutorialsRoute: ManageTutorialsRoute,
  ManageIndexRoute: ManageIndexRoute,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  CalendarRoute: CalendarRoute,
  ClubsRoute: ClubsRoute,
  ManageRoute: ManageRouteWithChildren,
  MyClubsRoute: MyClubsRoute,
  OwnerRoute: OwnerRoute,
  PendingRoute: PendingRoute,
  RequestAdminRoute: RequestAdminRoute,
  TeamsRoute: TeamsRoute,
  TutorialsRoute: TutorialsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ClubsClubIdRoute: ClubsClubIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
